name: Documentation Improvement
description: Report incorrect or missing documentation
title: "[DOC] "
labels: [documentation]

body:
  - type: textarea
    id: doc-location
    attributes:
      label: Location of the documentation
      description: >
        Please provide the location of the documentation, e.g. 
        "latents.mdlag.simulation.simulate" or the URL of the documentation.
    validations:
      required: true
  - type: textarea
    id: doc-problem
    attributes:
      label: Documentation problem
      description: >
        Please provide a description of what documentation you believe needs to be fixed
        or improved.
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested fix for documentation
      description: >
        Please explain the suggested fix and **why** it's better than the existing 
        documentation.
    validations:
      required: true
  - type: checkboxes
    id: code-of-conduct
    attributes:
      label: Code of Conduct
      description: >
        By submitting this issue, you agree to follow our 
        [Code of Conduct](../CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow the Latents Code of Conduct
          required: true