name: Feature Request
description: Suggest an idea for latents
title: "[ENH] "
labels: [enhancement, needs-triage]

body:
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched the existing issues to ensure this feature has not already been requested.
          required: true

  - type: checkboxes
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature request is this?
      options:
        - label: Adding new functionality to latents
        - label: Changing existing functionality in latents
        - label: Removing existing functionality in latents

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: >
        What problem would this feature solve?
    validations:
      required: true

  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: >
        Describe how the new feature would work. Include pseudocode if relevant.
    validations:
      required: true

  - type: textarea
    id: alternative
    attributes:
      label: Alternative Solutions
      description: >
        Describe any alternative solutions (existing functionality, 3rd party packages, etc.)
        that could address this need.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: >
        Any relevant GitHub issues, code examples, papers, or references.
